version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_FINE_TUNED_MODEL_ID: ${OPENAI_FINE_TUNED_MODEL_ID}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE}